# Lista de Exercícios 08 – Numpy

In [2]:
import numpy as np

## 1. Crie um array unidimensional com valores aleatórios e imprima o valor médio e a mediana.

In [12]:
arr = np.random.rand(5)
media = np.mean(arr)
mediana = np.median(arr)

print(f"Array: {arr}")
print(f"Média: {media}")
print(f"Mediana: {mediana}")

Array: [0.44965229 0.54982915 0.06611837 0.41445969 0.81636401]
Média: 0.4592847006059606
Mediana: 0.44965228803849533


# 2. Crie um array unidimensional com valores aleatórios e inverta a ordem dos elementos.

In [13]:
arr = np.random.rand(5)
arr_invertido = arr[::-1]

print(f"Array original: {arr}")
print(f"Array invertido: {arr_invertido}")

Array original: [0.17519648 0.81998779 0.50220583 0.95291733 0.66111549]
Array invertido: [0.66111549 0.95291733 0.50220583 0.81998779 0.17519648]


## 3. Crie um array unidimensional com valores aleatórios e calcule a diferença entre cada elemento e o próximo elemento.

In [15]:
arr = np.random.rand(5)
diferencas = np.diff(arr)

print(f"Array: {arr}")
print(f"Diferenças: {diferencas}")

Array: [0.39623286 0.8892836  0.0743549  0.66200533 0.27947618]
Diferenças: [ 0.49305075 -0.81492871  0.58765044 -0.38252915]


## 4. Crie uma matriz de zeros de tamanho 10x10 e adicione uma borda de valor 1.

In [16]:
# matriz 10x10 de zeros
matriz  = np.zeros((10, 10))
matriz 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# Pinta se for linha 1 ou coluna 1
matriz[(0,-1),:] = 1 # Bordas Superior e Inferior
matriz 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
matriz[:,(0,-1)] = 1 # Bordas Esquerda e Direita
matriz 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
# Pode fazer um por um também
matriz = np.zeros((10, 10))
matriz[0,:] = 1 # Primeira linha
matriz[-1,:] = 1 # Última linha
matriz[:,0] = 1 # Primeira coluna
matriz[:,-1] = 1 # Última coluna
matriz

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 5. Crie um array unidimensional com valores aleatórios e encontre o índice do valor mais próximo de um valor fornecido

In [25]:
arr = np.random.rand(5)
valor = 0.5
indice_proximo = np.abs(arr - valor).argmin()

print(f"Array: {arr}")
print(f"Índice do valor mais próximo de {valor}: {indice_proximo}")

Array: [0.2406362  0.1750002  0.64014782 0.55400307 0.57741141]
Índice do valor mais próximo de 0.5: 3


## 6. Crie um array unidimensional com valores aleatórios e encontre os valores únicos e suas contagens.

In [26]:
arr = np.random.randint(0, 10, size=10)
valores_unicos, contagens = np.unique(arr, return_counts=True)

print(f"Array: {arr}")
print(f"Valores únicos: {valores_unicos}")
print(f"Contagens: {contagens}")


Array: [2 2 2 0 9 4 0 0 9 2]
Valores únicos: [0 2 4 9]
Contagens: [3 4 1 2]
